env:
  browser: true
  es2021: true
extends: standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  camelcase: off
  quotes: ["error", "double"]
  semi: ["error", "always"]
