name: Build and Deploy
on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 */3 * * *'
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install and Build 🔧
        run: |
          export CHROME_DEVEL_SANDBOX=/opt/google/chrome/chrome-sandbox
          npm ci
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy to gh-pages.
